max_bytes: 5242880
backup_count: 5
logging:
  version: 1 # The only valid value at present is 1.
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s %(module)s:%(lineno)d %(levelname)s: %(message)s'
    info:
      format: '%(asctime)s %(name)s %(module)s:%(lineno)d %(levelname)s: %(message)s'
    error:
      format: '%(asctime)s %(name)s:%(process)d %(module)s:%(lineno)d %(levelname)s: %(message)s'
    redacted:
      (): 'utils.RedactedFormatter'
      patterns:
        - 'apikey=.{10}'
      format: '%(asctime)s %(module)s:%(lineno)d %(levelname)s: %(message)s'
  handlers:
    default:
      level: 'INFO'
      formatter: 'redacted'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
  loggers:
    '': # root logger
      handlers:
        - 'default'
      level: 'NOTSET'
    __main__: # if __name__ == '__main__'
      handlers:
        - 'default'
      level: 'DEBUG'
      propagate: False
    watcher:
      handlers:
        - 'default'
      level: 'INFO'
      propagate: False
    utils:
      handlers:
        - 'default'
      level: 'INFO'
      propagate: False
    simple_tricks:
      handlers:
        - 'default'
      level: 'INFO'
      propagate: False
    conduits:
      handlers:
        - 'default'
      level: 'INFO'
      propagate: False
