version: 1 # The only valid value at present is 1.
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s %(module)s:%(lineno)d %(levelname)s: %(message)s'
  info:
    format: '%(asctime)s %(name)s %(module)s:%(lineno)d %(levelname)s: %(message)s'
  error:
    format: '%(asctime)s %(name)s:%(process)d %(module)s:%(lineno)d %(levelname)s: %(message)s'
  redacted:
    (): 'utils.RedactedFormatter'
    patterns:
      - 'apikey=(.{10})'
      - "'apikey': '(.{10})'"
    format: '%(asctime)s %(module)s:%(lineno)d %(levelname)s: %(message)s'
handlers:
  default:
    level: 'NOTSET'
    formatter: 'redacted'
    class: 'logging.StreamHandler'
    stream: 'ext://sys.stdout'
  default_file_handler: # 이 핸들러의 이름은 고정
    level: 'NOTSET'
    formatter: 'redacted'
    class: 'logging.handlers.RotatingFileHandler'
    filename: '' # 로그를 파일에 저장하려면 파일 경로 입력
    mode: 'a'
    maxBytes: 5242880
    backupCount: 5
loggers:
  '': # root logger
    handlers:
      - 'default'
    level: 'NOTSET'
  __main__: # if __name__ == '__main__'
    handlers:
      - 'default'
    level: 'DEBUG'
    propagate: False
  watcher:
    handlers:
      - 'default'
    level: 'DEBUG'
    propagate: False
  utils:
    handlers:
      - 'default'
    level: 'DEBUG'
    propagate: False
  simple_tricks:
    handlers:
      - 'default'
    level: 'DEBUG'
    propagate: False
  conduits:
    handlers:
      - 'default'
    level: 'DEBUG'
    propagate: False
  watchdog:
    handlers:
      - 'default'
    level: 'DEBUG'
    propagate: False
  requests:
    handlers:
      - 'default'
    level: 'WARNING'
    propagate: False
  urllib3:
    handlers:
      - 'default'
    level: 'WARNING'
    propagate: False
